name: intro_slider_example
description: Demonstrates how to use the intro_slider plugin.
version: 2.0.0+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  
  intro_slider: ^3.0.10
    
  http: ^0.13.5
  fullscreen: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  

flutter:
  uses-material-design: true
